"""Report generation: human-readable Markdown + machine-readable JSON."""

from __future__ import annotations

import json
import time
from dataclasses import asdict
from typing import Optional

from . import __version__
from .analyzer import Assessment
from .scanner import ApRecord
from .wps import bin2hex

__all__ = ["build_reports", "write_reports"]

_DISCLAIMER = (
    "**Authorized use only.** This report was produced by WiFi-WPS-Attack-"
    "Tool for security assessment of networks you own or are explicitly "
    "authorized to test. Unauthorized access to computer networks is "
    "illegal in most jurisdictions."
)

_SEV_ICON = {"CRITICAL": "\U0001F534", "HIGH": "\U0001F7E0",
             "MEDIUM": "\U0001F7E1", "LOW": "\U0001F7E2", "INFO": "\u26AA"}


def _md_assessment(a: Assessment) -> str:
    lines = [
        f"## {a.bssid or '(no BSSID)'}  —  {a.ssid or '(unknown SSID)'}",
        "",
        f"- **Rating:** `{a.rating}`  (score {a.score})",
        f"- **Assessed:** {a.assessed_at}",
    ]
    if a.pin:
        lines.append(f"- **WPS PIN:** `{a.pin}`")
    if a.eta:
        lines.append(f"- **Online brute-force ETA (10^7 valid PINs, incl. "
                     f"lockout penalties): {a.eta[1]}**")
    if a.findings:
        lines += ["", "| Severity | Finding | Weight | Detail |",
                  "|---|---|---|---|"]
        for f in a.findings:
            icon = _SEV_ICON.get(f.severity, "")
            detail = f.detail.replace("|", "/")
            lines.append(f"| {icon} {f.severity} | {f.title} | "
                         f"{f.weight:+d} | {detail} |")
        for f in a.findings:
            if f.remediation:
                lines.append(f"- **Remediation [{f.fid}]:** {f.remediation}")
    if a.notes:
        lines += ["", "Notes:"] + [f"- {n}" for n in a.notes]
    lines.append("")
    return "\n".join(lines)


def build_markdown(assessments: list[Assessment],
                   title: str = "WPS Security Assessment",
                   scans: Optional[list[ApRecord]] = None,
                   extra: Optional[str] = None) -> str:
    now = time.strftime("%Y-%m-%d %H:%M:%S %Z", time.localtime())
    out = [
        f"# {title}",
        "",
        _DISCLAIMER,
        "",
        f"Generated by `wps-attack` v{__version__} on {now}.",
    ]
    if scans:
        out += ["", "## Scanned APs", "",
                "| BSSID | SSID | Ch | WPS | Locked | Signal |",
                "|---|---|---|---|---|---|"]
        for ap in scans:
            out.append(f"| {ap.bssid} | {ap.ssid or '-'} | {ap.channel} | "
                       f"{'Y' if ap.wps else 'N'} | "
                       f"{'Y' if ap.locked else 'N'} | {ap.signal_dbm} dBm |")
    if assessments:
        worst = max(a.score for a in assessments)
        out += ["", "## Summary", "",
                f"- APs assessed: **{len(assessments)}**",
                f"- Worst score: **{worst}**",
                "- Findings per AP below.", ""]
        for a in assessments:
            out.append(_md_assessment(a))
    if extra:
        out += [extra, ""]
    return "\n".join(out)


def build_json(payload: dict) -> str:
    payload.setdefault("tool", {"name": "wps-attack", "version": __version__,
                                "generated": time.strftime(
                                    "%Y-%m-%dT%H:%M:%S%z")})
    return json.dumps(payload, indent=2, sort_keys=False, default=str)


def write_reports(output_dir: str,
                  assessments: list[Assessment],
                  scans: Optional[list[ApRecord]] = None,
                  title: str = "WPS Security Assessment",
                  extra_md: Optional[str] = None,
                  json_payload: Optional[dict] = None,
                  filename_base: str = "wps-report") -> dict:
    """Write `<base>.md` and `<base>.json` into ``output_dir``.

    Returns a dict with the paths written.
    """
    import os
    os.makedirs(output_dir, exist_ok=True)
    md_path = os.path.join(output_dir, f"{filename_base}.md")
    json_path = os.path.join(output_dir, f"{filename_base}.json")

    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write(build_markdown(assessments, title, scans, extra_md))

    payload = json_payload or {
        "disclaimer": "Authorized use only.",
        "assessments": [a.to_dict() for a in assessments],
        "scans": [ap.to_dict() for ap in (scans or [])],
    }
    with open(json_path, "w", encoding="utf-8") as fh:
        fh.write(build_json(payload) + "\n")

    return {"markdown": md_path, "json": json_path}
